### ISSUE TITLE
数据集出错

### ISSUE THREAD

**Issue by ACBBZ** [secret2base/FederatedLearningOnRaspberry#1]
我去其他地方下载了minst数据集，但是用不了，这里data = MiniDataset(data['x'], data['y'])出错了。数据集是经过什么处理的吗？大佬能上传数据集吗？感谢

**Comment by secret2base** [comment]
这份工程是很早之前的了，我只是为了练习使用Git把它上传了上来。数据集需要进行重构和划分，具体分成什么结果可以参看神经网络的结构。最近在忙毕业设计，空闲下来可能会整理数据集的。
